PYThon/gymPanda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import smtplib
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('tintuc/', include('tintuc.urls')),
    path('gioithieu/', include('gioithieu.urls')),
    path('team/', include('team.urls')),
    path('contact', include('contact.urls')),
    path('khuyenmai/',include('promotions.urls')),
    path('course/', include('course.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PYThon/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.getHomeView, name='index'),
    path('cart', views.getCartView, name='cart'),
]

PYThon/product/urls.py
from django.urls import path
from . import views
from .views import ProductDetail

app_name = 'product'
urlpatterns = [
    path('', views.getProductView, name='product_view'),
    # path('detail/<int:id_product>', views.getProductDetailsView, name='product_detail'),
    path('detail/<int:id_product>', ProductDetail.as_view(), name='product_detail'),
    path('type/<int:id_category>', views.getProductTypeView, name='product_type'),
    path('search/', views.searchProduct, name='product_search'),
]

PYThon/product/models.py
from django.db import models
from django.db import connections
# Create your models here.

class Category(models.Model):
    ma_loai_san_pham = models.AutoField(primary_key=True, unique=True)
    tenloai = models.CharField(max_length=100, default='')
    trang_thai = models.IntegerField(null=False, default=1)
    class Meta:
        db_table = "loai_san_pham"
    
    def __str__(self):
        # return self.ma_loai_san_pham, self.tenloai
        template = '{0.ma_loai_san_pham}'
        return template.format(self)


class Manufacturer(models.Model):
    ma_nha_san_xuat = models.AutoField(primary_key=True, unique=True)
    tennsx = models.CharField(max_length=100, default='')
    sdt = models.CharField(max_length=100, default='', null=False)
    email = models.EmailField(max_length = 254)
    class Meta:
        db_table = "nha_san_xuat"
    
    def __str__(self):
        return self.tennsx

class Product(models.Model):
    masp = models.AutoField(primary_key=True, unique=True)
    tensp = models.CharField(max_length=100, default='')
    chi_tiet_sp = models.TextField(null=False, default='')
    xuat_xu = models.CharField(max_length=100)
    hinh = models.ImageField(upload_to='product_imgs/', null=False)
    ma_nha_san_xuat = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, db_column='ma_nha_san_xuat')
    nam_san_xuat = models.DateField()
    ma_loai_san_pham = models.ForeignKey(Category, on_delete=models.CASCADE, db_column='ma_loai_san_pham')
    gia = models.IntegerField(null=True, default=0)
    discount = models.IntegerField(null=True, default=0)
    dvt = models.CharField(max_length=5, default='VND')
    class Meta:
        db_table = "san_pham"
    
    def __str__(self):
        return self.tensp

        
    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(masp__in = ids)

PYThon/product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from product.models import Product, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import View
from promotions.models import promotions
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
# def getCategory_Navbar(request):
#     result = Category.objects.all()
#     nameCategory = {
#         'objects': result
#     }
#     return render(request, 'navbar.html', nameCategory)

def getProductView(request):
    result = Product.objects.all()
    for item in result :
        km = promotions.objects.filter(ma_loai_san_pham = item.ma_loai_san_pham)
        if km.count != 0 :
            for value in km :
                item.discount = item.gia - (item.gia * value.phantram_giam/100)
                item.save()
        else:
            item.discount = item.gia
            item.save()

    page = request.GET.get('page', 1)

    paginator = Paginator(result, 9)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'product/product.html', {'products': products}) 


class ProductDetail(View):
    def get(self, request, id_product):
        cart = request.session.get('cart')
        if not cart:
            request.session.cart = {}
        # obj = get_object_or_404(Product, id = id_product)
        obj = Product.objects.get(pk = id_product)
        obj_cat = Category.objects.all()
        obj_type = Product.objects.all()
        km = promotions.objects.filter(ma_loai_san_pham = obj.ma_loai_san_pham)
        if km.count != 0 :
            for value in km :
                obj.discount = obj.gia - (obj.gia * value.phantram_giam/100)
                obj.save()
        else:
            obj.discount = obj.gia
            obj.save()
        return render(request, 'product/product_details.html', {'product': obj, 'categories': obj_cat, 'type': obj_type,'km':km}) 

    def post(self, request, id_product):
        if not request.session.get('customer_email'):
            return redirect('customer:login')
        else:
            product = request.POST.get('product')
            remove = request.POST.get('remove')
            cart = request.session.get('cart')
            if cart:
                quantity = cart.get(product)
                if quantity:
                    if remove:
                        if quantity <= 1:
                            cart.pop(product)
                        else:
                            cart[product] = quantity - 1
                    else:
                        cart[product] = quantity + 1
                else:
                    cart[product] = 1
            else:
                cart = {}
                cart[product] = 1
            
            request.session['cart'] = cart
            print('cart:', request.session['cart'])
            return redirect('product:product_detail', id_product) 


# def getProductDetailsView(request, id_product):
#     # obj = get_object_or_404(Product, id = id_product)
#     obj = Product.objects.get(pk = id_product)
#     obj_cat = Category.objects.all()
#     obj_type = Product.objects.all()
#     return render(request, 'product/product_details.html', {'product': obj, 'categories': obj_cat, 'type': obj_type}) 


def getProductTypeView(request, id_category):
    result = Product.objects.filter(ma_loai_san_pham = id_category)
    obj_cat = Category.objects.get(pk = id_category)
    km = promotions.objects.filter(ma_loai_san_pham = id_category)
    if km.count != 0 :
        for value in km :
            for item in result : 
                item.discount = item.gia - (item.gia * value.phantram_giam/100)
                item.save()
    else:
        for item in result : 
            item.discount = item.gia
            item.save()
    return render(request, 'product/product_type.html', {'list': result, 'category': obj_cat ,'promotions': km})


def searchProduct(request):
    try:
        s = request.GET.get('s')
    except:
        s = None
    if s:
        products = Product.objects.filter(tensp__icontains = s)
        count = products.count()
        context = { 'query': s, 'list': products, 'count': count }
        template = 'product/product_search.html'
    else:
        context = {}
        template = 'home/index.html'

    return render(request, template, context)

PYThon/product/templates/product/product.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% load cart %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'home/img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Sản phẩm</h2>
                        <div class="bt-option">
                            <a href="{% url 'home:index' %}">Trang chủ</a>
                            <span>Sản phẩm</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Team Section Begin -->
    <section class="team-section team-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="team-title">
                        <div class="section-title">
                            <span>Sản phẩm</span>
                            <h2>Hỗ trợ tốt nhất cho bạn</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for item in products %}
                    <div class="col-lg-4 col-sm-6">
                        <!-- {% static 'home/img/team/team-1.jpg' %} -->
                        <div class="ts-item set-bg" data-setbg="{{ item.hinh.url }}">
                            <!-- <img src="{{ item.hinh.url }}"> -->
                            <div class="ts_text">
                                <h4>{{ item.tensp }}</h4>
                                <h5 style="color: aliceblue;">
                                    {% if item.discount == 0 or item.discount == NULL %}
                                        {{ item.gia | intcomma }}
                                    {% else %}
                                         {{ item.discount | intcomma }}
                                    {% endif %}
                                </h5><h6 style="color: #f36100;">{{ item.dvt }}</h6>
                                <a href="{% url 'product:product_detail' item.masp %}" class="primary-btn">xem chi tiết</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-sm-12">
                    {% if products.has_other_pages %}
                        <ul class="pagination justify-content-center">
                            {% if products.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}" style="color: #f36100;">&laquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><span class="page-link" style="color: #f36100;">&laquo;</span></li>
                            {% endif %}

                            {% for i in products.paginator.page_range %}
                                {% if products.number == i %}
                                    <li class="page-item active"><span class="page-link" style="background-color: #f36100; border: antiquewhite;">{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}" style="color: #f36100;">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if products.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ products.nex_page_number }}" style="color: #f36100;">&raquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><span class="page-link" style="color: #f36100;">&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                    <!-- <nav>
                        <ul class="pagination justify-content-center">
                          <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                          <li class="page-item active"><a class="page-link" href="#">1</a></li>
                          <li class="page-item"><a class="page-link" href="#">2</a></li>
                          <li class="page-item"><a class="page-link" href="#">3</a></li>
                          <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                        </ul>
                      </nav> -->
                </div>
            </div>
        </div>
    </section>
    <!-- Team Section End -->

{% endblock %}

PYThon/product/templates/product/product_details.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load cart %}


{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'home/img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Chi tiết sản phẩm</h2>
                        <div class="bt-option">
                            <a href="{% url 'home:index' %}">Trang chủ</a>
                            <a href="{% url 'product:product_view' %}">Sản phẩm</a>
                            <span>Chi tiết</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    <!-- Class Details Section Begin -->
    <section class="class-details-section spad">
        <div class="container"> 
            <div class="row">
                <div class="col-lg-9">
                    <div class="class-details-text">
                        <div class="cd-trainer">
                            <div class="row">
                                {% if product != None %}
                                    <div class="col-md-6">
                                        <div class="cd-trainer-pic">
                                            <img src="{{ product.hinh.url }}" alt="">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="cd-trainer-text">
                                            <div class="trainer-title">
                                                <h4 style="color: #f36100;">{{ product.tensp }}</h4>
                                                <span style="font-weight: bold; color: white;">Loại sản phẩm :</span><span> {{ product.ma_loai_san_pham}}</span>
                                            </div>
                                            <p style="text-align: justify;">{{ product.chi_tiet_sp }}</p>
                                            <ul class="trainer-info">
                                                <li><span>Mã sản phẩm</span>{{ product.masp }}</li>
                                                <li><span>Xuất xứ</span>{{ product.xuat_xu }}</li>
                                                <li><span>Nhà sản xuất</span>{{ product.ma_nha_san_xuat }}</li>
                                                <li><span>Năm sản xuất</span>{{ product.nam_san_xuat | date:"Y" }}</li>
                                                {% if km.count != 0 %}
                                                    <li><span>Giá Cũ</span>
                                                            <n style="text-decoration: line-through;">{{ product.gia  | intcomma }}</n>
                                                            <span style="color: #f36100; font-weight: bold;">{{ product.dvt }}</span>
                                                    </li>
                                                    <li><span>Giá mới</span>
                                                            {{ product.discount | intcomma }}
                                                        <span style="color: #f36100; font-weight: bold;">{{ product.dvt }} {% for value in km %}
                                                            {% if product.ma_loai_san_pham ==  value.ma_loai_san_pham %}
                                                        ( -{{ value.phantram_giam }} %)
                                                            {% endif %}
                                                        {% endfor %}</span>
                                                        
                                                    </li>
                                                {% else %}
                                                    <li><span>Giá</span>
                                                    {% if product.discount == 0 or  product.discount == NULL %}
                                                        {{ product.gia  | intcomma }}
                                                        
                                                    {% else %}
                                                        {{ product.discount  | intcomma }}
                                                    {% endif %}

                                                    <span style="color: #f36100; font-weight: bold;">{{ product.dvt }}</span>
                                                    
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                        {% if product.ma_loai_san_pham == 6 %}
                                            <p>
                                                <h2 style="color: #f36100;">Liên hệ: 0903876543 để được tư vấn.</h2>
                                            </p>
                                        {% elif  product.ma_loai_san_pham == 7  %}
                                            <p>
                                                <h2 style="color: #f36100;">Liên hệ: 0903876543 để được tư vấn.</h2>
                                            </p>
                                        {% elif  product.ma_loai_san_pham == 8  %}
                                            <p>
                                                <h2 style="color: #f36100;">Liên hệ: 0903876543 để được tư vấn.</h2>
                                            </p>
                                        {% else %}
                                            <!-- <p>
                                                <strong style="color: white;">Số lượng: </strong>
                                                <input type="number" value="1" min="1" max="5">
                                            </p> -->
                                            <div class="row no-gutters">
                                                {% if product|is_in_cart:request.session.cart %}
                                                    <div class="row" >
                                                        <form action="" class="col-3" method="POST">
                                                            {% csrf_token %}
                                                            <input hidden type="text" name="product" value="{{ product.masp }}">
                                                            <input hidden type="text" name="remove" value="True">
                                                            <input type="submit" value=" - " style="border-radius: 0px; height: 45px;" class="btn btn-block btn-light">
                                                        </form>
                                                        <div class="text-center col" style="color: white;">{{product|cart_quantity:request.session.cart}} trong giỏ hàng</div>
                                                        <form action="" class="col-3" method="POST">
                                                            {% csrf_token %}
                                                            <input hidden type="text" name="product" value="{{ product.masp }}">
                                                            <input type="submit" value=" + " style="border-radius: 0px; height: 45px;" class="btn btn-block btn-light">
                                                        </form>
                                                    </div>
                                                {% else %}
                                                    <form action="" method="POST" class="btn-block">
                                                        {% csrf_token %}
                                                        <input hidden type="text" name="product" value="{{ product.masp }}">
                                                        <input type="submit" class="primary-btn btn-normal appoinment-btn" style="float: left;" value="Đặt hàng"/>
                                                    </form>
                                                {% endif %}
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            </div>
                            <br><hr style="background-color: white;">
                            <div class="row">
                                <div style="margin-left: 2vh;">
                                    <h3 class="title" style="color:  #f36100;">Góp ý</h3><br>
                                    <table>
                                        <tr>
                                            <td><label style="color: white;" for="name">Username</label></td>
                                            <td><input name="name" type="text"></td>
                                        </tr>
                                        <tr>
                                            <td><label style="color: white;" for="email">Email</label></td>
                                            <td><input name="email" type="email"></td>
                                        </tr>
                                        <tr>
                                            <td><label style="color: white;" for="review">Nội dung</label></td>
                                            <td><textarea name="review" id="" rows="10" style="width: 40vw;"></textarea></td>
                                        </tr>
                                    </table>
                                    <a href="#" class="primary-btn btn-normal appoinment-btn" style="float: left;">Đăng bài</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-9">
                    <div class="sidebar-option">
                        <div class="so-categories">
                            <h5 class="title">Danh mục sản phẩm</h5>
                            <ul>
                                {% for item in categories %}
                                    <li><a href="{% url 'product:product_type' item.ma_loai_san_pham %}">{{ item.tenloai }} <span>{{ item.ma_loai_san_pham.Count }}</span></a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="so-latest">
                            <h5 class="title">Sản phẩm khuyến mãi</h5>
                            <div class="latest-large set-bg" data-setbg="{% static 'home/img/sidebar-banner.jpg' %}">
                                <div class="ll-text">
                                    <h5><a href="#">More</a></h5>
                                </div>
                            </div>
                            <div class="latest-item">
                                <div class="li-pic">
                                    <img src="{% static 'home/img/letest-blog/latest-1.jpg' %}" alt="" width="50vw" height="50vh">
                                </div>
                                <div class="li-text">
                                    <h6><a href="#">Trọn gói boxing</a></h6>
                                    <span class="li-time">Aug 15, 2019</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Team Section Begin -->
            <section class="team-section spad">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="team-title">
                                <div class="section-title">
                                    <h2 style="color: #f36100;">Sản phẩm liên quan</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="ts-slider owl-carousel">
                            {% for item in type %}
                                {% if item.ma_loai_san_pham == product.ma_loai_san_pham %}
                                    <div class="col-lg-4">
                                        <div class="ts-item set-bg" data-setbg="{{ item.hinh.url }}">
                                            <div class="ts_text">
                                                <h4>{{ item.tensp }}</h4>
                                                <h5 style="color: aliceblue;">{{ item.gia | intcomma }}</h5><h6 style="color: #f36100;">{{ item.dvt }}</h6>
                                                <a href="{% url 'product:product_detail' item.masp %}" class="primary-btn">xem chi tiết</a>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </section>
            <!-- Team Section End -->
        </div>
    </section>
    <!-- Class Details Section End -->
{% endblock %}

PYThon/product/templates/product/product_search.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'home/img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Tìm kiếm sản phẩm</h2>
                        <div class="bt-option">
                            <a href="{% url 'home:index' %}">Trang chủ</a>
                            <span>Tìm kiếm</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Team Section Begin -->
    <section class="team-section team-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="team-title">
                        <div class="section-title">
                            <span>Sản phẩm</span>
                            <h2>Từ khóa: {{ query }} ({{ count }} kết quả)</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for item in list %}
                    <div class="col-lg-4 col-sm-6">
                        <div class="ts-item set-bg" data-setbg="{{ item.hinh.url }}">
                            <div class="ts_text">
                                <h4>{{ item.tensp }}</h4>
                                <h5 style="color: aliceblue;">
                                {% if item.discount == 0 || item.discount == NULL  %}
                                    {{ item.gia | intcomma }}
                                {% else %}
                                    {{ item.discount | intcomma }}
                                {% endif %}    
                                

                                </h5><h6 style="color: #f36100;">{{ item.dvt }}</h6>
                                <a href="{% url 'product:product_detail' item.masp %}" class="primary-btn">xem chi tiết</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Team Section End -->

{% endblock %}