PYThon/course/urls.py
from django.urls import path
from . import views

app_name = 'course'
urlpatterns = [
    path('', views.getCourseView, name='course_view'),
    path('course/<int:id_loaimon>', views.getLoaimontapluyenView,
         name='loai_mon_tap_luyen_view'),
    
]

PYThon/gymPanda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import smtplib
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('tintuc/', include('tintuc.urls')),
    path('gioithieu/', include('gioithieu.urls')),
    path('team/', include('team.urls')),
    path('contact', include('contact.urls')),
    path('khuyenmai/',include('promotions.urls')),
    path('course/', include('course.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PYThon/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.getHomeView, name='index'),
    path('cart', views.getCartView, name='cart'),
]

PYThon/order/urls.py
from django.urls import path
from . import views
from .views import CheckOut

app_name = 'order'
urlpatterns = [
    path('checkout', CheckOut.as_view(), name='checkout'),
]

PYThon/team/urls.py
from django.urls import path
from . import views
app_name = 'team'
urlpatterns = [ 
    path('', views.getteamView, name='team_view'),
]

PYThon/tintuc/urls.py
from django.urls import path
from . import views

app_name = 'tintuc' 
urlpatterns = [
    path('', views.gettintucView, name='tintuc_view'),
     path('chitiet/<int:id_tintuc>', views.getloaitintucView, name='loai_tin_view'),
]

PYThon/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Gym Template">
    <meta name="keywords" content="Gym, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gym Panda</title>
    <link rel="icon" href="{% static 'home/img/favicon.ico' %}">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/flaticon.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/barfiller.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    {% include 'navbar.html' %}

    {% block content %}
    
    {% endblock %}

    {% include 'footer.html' %}

    <!-- Js Plugins -->
    <script src="{% static 'home/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.barfiller.js' %}"></script>
    <script src="{% static 'home/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/js/main.js' %}"></script>



</body>

</html>

PYThon/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load cart %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'home/img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Giỏ hàng</h2>
                        <div class="bt-option">
                            <a href="{% url 'home:index' %}">Trang chủ</a>
                            <span>Giỏ hàng</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Cart Section Begin -->
    <section class="contact-section spad">
        <div class="container">
            <div class="border rounded p-5 m-6">
                <p class="display-4">GIỎ HÀNG CỦA BẠN</p>
                <hr> 
                <table class="table" style="color: white;">
                    <thead  style="color: #f36100;">
                        <tr>
                            <th>STT</th>
                            <th>Hình ảnh</th>
                            <th>Tên sản phẩm</th>
                            <th>Giá</th>
                            <th>Số lượng</th>
                            <th>Thành tiền</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in products %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><img style="height: 80px;" src="{{ product.hinh.url }}" alt=""></td>
                                <td>{{ product.tensp }}</td>
                                <td>
                                {% if product.discount == 0 or product.discount == null  %}
                                    {{ product.gia | intcomma }}
                                {% else %}
                                    {{ product.discount | intcomma }}
                                {% endif %}
                                </td>
                                <td>{{ product|cart_quantity:request.session.cart }}</td>
                                <td>{{ product|price_total:request.session.cart|intcomma }} <span style="color: #f36100;">VND</span></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot style="font-size: 16px;">
                        <tr>
                            <th colspan="4"></th>
                            <th style="color: #f36100;">Tổng thành tiền</th>
                            <th>{{ products|total_cart_price:request.session.cart|intcomma }} <span style="color: #f36100;">VND</span></th>
                        </tr>
                    </tfoot>
                </table>
                <hr>
                <div class="m-3 p-3">
                    <a href="#" class="primary-btn btn-normal appoinment-btn" data-toggle="modal" data-target="#exampleModal">Xác nhận đơn hàng</a>
                </div>
            </div>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">NHẬP THÔNG TIN XÁC NHẬN ĐƠN HÀNG</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <div class="m-2 p-3">
                            <form action="{% url 'order:checkout' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="">Địa chỉ</label>
                                    <input type="text" name="diachi" class="form-control" aria-describedby="helpId" required>
                                </div>
                                <div class="form-group">
                                    <label for="">Số điện thoại</label>
                                    <input type="text" name="sdt" class="form-control" aria-describedby="helpId" required>
                                </div>
                                <div class="form-group">
                                    <label for="">Gmail</label>
                                    <input type="text" name="gmail" class="form-control" aria-describedby="helpId" required>
                                </div>
                                <input type="submit" class="btn btn-outline-dark col-lg-6" value="Xác nhận">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Cart Section End -->
{% endblock %}

PYThon/templates/footer.html
{% load static %}
<!-- Get In Touch Section Begin -->
<div class="gettouch-section">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="gt-text">
                    <i class="fa fa-map-marker"></i>
                    <p>180 Cao Lỗ , Phường 4, Quận 8, Thành phố Hồ Chí Minh, Vietnam<br/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="gt-text">
                    <i class="fa fa-mobile"></i>
                    <ul>
                        <li>113-114-115</li>
                        <li>1900-1091</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="gt-text email">
                    <i class="fa fa-envelope"></i>
                    <p>duyenyangho@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Get In Touch Section End -->
<!-- Footer Section Begin -->
<section class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="fs-about">
                    <div class="fa-logo">
                        <a href="#"><img src="{% static 'home/img/logo.png' %}" alt=""></a>
                    </div>
                    <p>Sức khỏe, năng lượng là nguồn năng lực sống của bản thân</p>
                    <div class="fa-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa  fa-envelope-o"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="fs-widget">
                    <h4>Useful links</h4>
                    <ul>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Lớp học</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="fs-widget">
                    <h4>Support</h4>
                    <ul>
                        <li><a href="#">Đăng nhập</a></li>
                        <li><a href="#">Đăng ký</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="fs-widget">
                    <h4>Mẹo & Hướng dẫn</h4>
                    <div class="fw-recent">
                        <h6><a href="#">Thể chất có thể giúp ngăn ngừa trầm cảm, lo âu</a></h6>
                        <ul>
                            <li>3 min read</li>
                            <li>20 Comment</li>
                        </ul>
                    </div>
                    <div class="fw-recent">
                        <h6><a href="#">Thể dục: Bài tập tốt nhất để giảm mỡ bụng và săn chắc ...</a></h6>
                        <ul>
                            <li>3 min read</li>
                            <li>20 Comment</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="copyright-text">
                    <p>
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Footer Section End -->

PYThon/templates/navbar.html
{% load static %}
<!-- Offcanvas Menu Section Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="canvas-close">
        <i class="fa fa-close"></i>
    </div>
    <div class="canvas-search search-switch">
        <i class="fa fa-search"></i>
    </div>
    <nav class="canvas-menu mobile-menu">
        <ul>
            <li><a href="{% url 'home:index' %}">Trang chủ</a></li>
            <li><a href="./about-us.html">Giới thiệu</a></li>
            <li><a href="{% url 'tintuc:tintuc_view' %}">Tin tức</a></li>
            <li><a href="{% url 'course:course_view' %}">Khóa tập</a></li>
            <li><a href="{% url 'product:product_view' %}">Sản phẩm</a></li>
            <li><a href="./team.html">Team</a></li>
            <li><a href="#">Sản phẩm</a>
                <ul class="dropdown">
                    <li><a href="#">PROTEIN - Whey</a></li>
                    <li><a href="#">Dụng Cụ Hổ Trợ</a></li>
                    <li><a href="#">Thời trang Gym</a></li>
                    <li><a href="#">Máy Gym gia đình</a></li>
                </ul>
            </li>
            <li><a href="#">Liên hệ</a></li>
        </ul>
    </nav>
    <div id="mobile-menu-wrap"></div>
    <!-- <div class="canvas-social">
        <a href="#"><i class="fa fa-shopping-cart"></i></a>
    </div> -->
    <a href="#"><i class="fa fa-shopping-cart"></i></a>
    <a href="#"><i class="fa fa-user"></i></a>
    <a href="#"><i class="fa fa-plus"></i></a>
</div>
<!-- Offcanvas Menu Section End -->

<!-- Header Section Begin -->
<header class="header-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2">
                <div class="logo">
                    <a href="{% url 'home:index' %}">
                        <img src="{% static 'home/img/logo.png' %}" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="nav-menu">
                    <ul>
                        <li><a href="{% url 'home:index' %}">Trang chủ</a></li>
                        <li><a href="{% url 'gioithieu:gioithieu_view' %}">Giới thiệu</a></li>
                        <li><a href="{% url 'tintuc:tintuc_view' %}">Tin tức</a>
                            <ul class="dropdown">
                                <li><a href="{% url 'promotions:index' %}">Khuyến Mãi <span class="badge badge-secondary">New</span></a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'course:course_view' %}">Khóa tập</a></li>
                        <!-- <li><a href="./services.html">Services</a></li> -->
                        <li><a href="{% url 'team:team_view' %}">Our Team</a></li>
                        <li><a href="{% url 'product:product_view' %}">Sản phẩm</a></li>
                        <li><a href="{% url 'contact:contact_view' %}">Liên hệ</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-4">
                <div class="top-option">
                    <div class="to-search search-switch">
                        <i class="fa fa-search"></i>
                    </div>
                    <div class="to-social">
                        {% if request.session.customer_name == null %}
                            <a href="{% url 'customer:login' %}"><i class="fa fa-user"></i> Đăng nhập</a>
                            <a href="{% url 'customer:register' %}"><i class="fa fa-plus"></i> Đăng ký</a>
                        {% else %}
                            <i class="fa fa-user" style="color: white;">  Chào, {{ request.session.customer_name }}</i><a href="{% url 'customer:logout' %}">Đăng xuất</a>
                            {% if request.session.cart.keys|length != 0 %}
                                <a href="{% url 'home:cart' %}"><i class="fa fa-shopping-cart"></i> Giỏ hàng
                                    <span style="background-color: #f36100;" class="badge badge-info">{{ request.session.cart.keys|length }}</span>
                                </a>
                            {% else %}
                                <a href="{% url 'home:index' %}"><i class="fa fa-shopping-cart"></i> Giỏ hàng
                                    <span style="background-color: #f36100;" class="badge badge-info">{{ request.session.cart.keys|length }}</span>
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="canvas-open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header End -->

<!-- Search model Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" action="{% url 'product:product_search' %}">
            <input type="text" id="search-input" name="s" placeholder="Tìm kiếm sản phẩm">
            <button style="border-radius: 0px;" type="submit" class="btn btn-outline-light text-dark btn-lg"><b>Tìm kiếm</b></button>
        </form>
    </div>
</div>
<!-- Search model end -->