PYThon/gymPanda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import smtplib
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('tintuc/', include('tintuc.urls')),
    path('gioithieu/', include('gioithieu.urls')),
    path('team/', include('team.urls')),
    path('contact', include('contact.urls')),
    path('khuyenmai/',include('promotions.urls')),
    path('course/', include('course.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PYThon/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.getHomeView, name='index'),
    path('cart', views.getCartView, name='cart'),
]

PYThon/promotions/urls.py
from django.urls import path
from . import views
from .views import Promotions_Product

app_name = 'promotions'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:id_category>', views.Promotions_Product, name='product'),
    # path('chitiet/<int:id_category>', views.chitiet , name = 'chitiet'),
]

PYThon/promotions/models.py
from django.db import models
from django.db import connections
from product.models import Category
# Create your models here.


class promotions(models.Model):
    ma_chuong_trinh = models.AutoField(primary_key=True, unique=True)
    ten_chuong_trinh = models.CharField(max_length=150, default='')
    ma_loai_san_pham = models.ForeignKey(Category, on_delete=models.CASCADE, db_column='ma_loai_san_pham')
    noi_dung = models.TextField(null=False, default='')
    phantram_giam = models.IntegerField(null=False, default=1)
    ngay_bat_dau = models.DateField()
    thoi_gian_ket_thuc = models.DateField()
    class Meta:
        db_table = "chuong_trinh_khuyen_mai"
    
    def __str__(self):
        return self.ten_chuong_trinh

PYThon/promotions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from promotions.models import promotions 
from product.models import Product, Category
from django.views import View

# Create your views here.
def index(request):
	km =  promotions.objects.all()
	return render(request , 'promotions/index.html' , {'promotions': km} )



# def chitiet(request, category_id):
# 	result = Product.objects.filter(ma_loai_san_pham = category_id)

#     return render(request, 'promotions/details.html', {'list': result })


def Promotions_Product(request, id_category):
    result = Product.objects.filter(ma_loai_san_pham = id_category)
    obj_cat = Category.objects.get(pk = id_category)
    km = promotions.objects.filter(ma_loai_san_pham = id_category)
    if( km.count != 0 ):
        for value in km :
            for item in result : 
                item.discount = item.gia - (item.gia * value.phantram_giam/100)
                item.save()
    else:
    	for item in result : 
                item.discount = item.gia
                item.save()
    return render(request, 'product/product_type.html', {'list': result, 'category': obj_cat, 'promotions': km } )

PYThon/promotions/templates/promotions/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load cart %}


{% block content %}
<!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'home/img/banner-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Khuyến mãi</h2>
                        <div class="bt-option">
                            <a href="{% url 'home:index' %}">Trang chủ</a>
                            <span>Khuyến mãi</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
 
	<!-- Blog Section Begin -->
    <section class="blog-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 p-0">
                    {% for item in promotions  %}
                    <div class="blog-item">
                        <div class="bi-pic">
                            <img src="{% static 'home/img/blog/blog-1.jpg' %}" alt="">
                        </div>
                        <div class="bi-text">
                            <h5><a href="{% url 'promotions:product' item.ma_loai_san_pham %}">{{ item.ten_chuong_trinh }}</a></h5>
                            <ul>
                                <li>by Huy</li>
                                <li>{{ item.ngay_bat_dau}}</li>
                                <li>20 Comment</li>
                            </ul>
                            <p>{{ item.noi_dung }}</p>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="blog-pagination">
                        <a href="#">1</a>
                        <a href="#">2</a>
                        <a href="#">3</a>
                        <a href="#">Next</a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-8 p-0">
                <div class="sidebar-option">
                    <div class="so-categories">
                        <h5 class="title">THỂ LOẠI</h5>
                        <ul>
                            <li><a href="#">Yoga <span>12</span></a></li>
                            <li><a href="#">Chạy <span>32</span></a></li>
                            <li><a href="#">Giảm cân <span>86</span></a></li>
                            <li><a href="#">Cario <span>25</span></a></li>
                            <li><a href="#">Cơ thể <span>36</span></a></li>
                            <li><a href="#">Dinh dưỡng<span>15</span></a></li>
                        </ul>
                    </div>
                    <div class="so-latest">
                        <h5 class="title">BÀI ĐĂNG NỔI BẬT</h5>
                        <div class="latest-large set-bg" data-setbg="img/letest-blog/latest-1.jpg">
                            <div class="ll-text">
                                <h5><a href="https://baoquocte.vn/tau-ca-trung-quoc-tap-ket-tai-da-ba-dau-o-bien-dong-thay-gi-tu-phan-ung-cua-my-144091.html">Tàu cá Trung Quốc tập kết tại Đá Ba Đầu ở Biển Đông: Thấy gì từ phản ứng của Mỹ?</a></h5>
                                <ul>
                                    <li>Aug 20, 2019</li>
                                    <li>20 Comment</li>
                                </ul>
                            </div>
                        </div>
                        <div class="latest-item">
                            <div class="li-pic">
                                <img src="img/letest-blog/latest-2.jpg" alt="">
                            </div>
                            <div class="li-text">
                                <h6><a href="https://suckhoedoisong.vn/ket-qua-giai-trinh-tu-gen-n191413.html">Các ca mắc mới COVID-19 nhiễm biến chủng của Ấn Độ và Anh</a></h6>
                                <span class="li-time">Aug 15, 2019</span>
                            </div>
                        </div>
                        <div class="latest-item">
                            <div class="li-pic">
                                <img src="img/letest-blog/latest-3.jpg" alt="">
                            </div>
                            <div class="li-text">
                                <h6><a href="https://tienphong.vn/nu-nhan-vien-massage-nghi-nhiem-covid-19-o-da-nang-da-tiep-xuc-nhung-ai-post1333433.tpo">Nữ nhân viên massage nghi nhiễm COVID-19 ở Đà Nẵng đã tiếp xúc những ai?</a></h6>
                                <span class="li-time">Aug 15, 2019</span>
                            </div>
                        </div>
                        <div class="latest-item">
                            <div class="li-pic">
                                <img src="img/letest-blog/latest-4.jpg" alt="">
                            </div>
                            <div class="li-text">
                                <h6><a href="http://baochinhphu.vn/chi-dao-quyet-dinh-cua-chinh-phu-thu-tuong-chinh-phu/phai-co-nhung-dot-pha-moi-de-khcn-tro-thanh-suc-manh-dong-luc-thuc-su/430047.vgp">Phải có những đột phá mới để KH&CN trở thành sức mạnh, động lực thực sự</a></h6>
                                <span class="li-time">Aug 15, 2019</span>
                            </div>
                        </div>
                        <div class="latest-item">
                            <div class="li-pic">
                                <img src="img/letest-blog/latest-5.jpg" alt="">
                            </div>
                            <div class="li-text">
                                <h6><a href="https://baoquocte.vn/bo-truong-quoc-phong-my-austin-se-co-chuyen-tham-dau-tien-toi-dong-nam-a-144135.html">Bộ trưởng Quốc phòng Mỹ Austin sẽ có chuyến thăm đầu tiên tới Đông Nam Á</a></h6>
                                <span class="li-time">Aug 15, 2019</span>
                            </div>
                        </div>
                    </div>
                    <div class="so-tags">
                        <h5 class="title">Các thẻ phổ biến</h5>
                        <a href="#">Tập thể dục</a>
                        <a href="#">Xây dựng cơ thể</a>
                        <a href="#">Yoga</a>
                        <a href="#">Giảm cân</a>
                        <a href="#">Proffeponal</a>
                        <a href="#">Streching</a>
                        <a href="#">Cardio</a>
                        <a href="#">Boxing</a>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- Blog Section End -->




{% endblock %}